import 'package:flutter/material.dart';
import 'package:islami/Quran/chapters.dart';

class QuranTab extends StatelessWidget {
  QuranTab({super.key});

  final List<String> names = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Expanded(
            flex: 1,
            child: Image.asset("lib/assets/images/qur2an_screen_logo.png")),
        Divider(
          color: Theme.of(context).primaryColor,
          thickness: 3,
          height: 2,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const Expanded(
              child: Text(
                "رقم السورة",
                textAlign: TextAlign.center,
                style: TextStyle(
                    fontFamily: "ElMessiri",
                    fontWeight: FontWeight.bold,
                    fontSize: 25),
              ),
            ),
            Container(
              width: 3,
              height: 50,
              color: Theme.of(context).primaryColor,
            ),
            const Expanded(
              child: Text("اسم السورة",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      fontFamily: "ElMessiri",
                      fontWeight: FontWeight.bold,
                      fontSize: 25)),
            )
          ],
        ),
        Divider(
          color: Theme.of(context).primaryColor,
          thickness: 3,
          height: 2,
        ),
        Expanded(
          flex: 2,
          child: ListView.builder(
              itemBuilder: (context, index) {
                return Chapters(
                  title: names[index],
                  index: index,
                );
              },
              // separatorBuilder: (context, index) => Container(
              //       color: Theme.of(context).primaryColor,
              //       width: double.infinity,
              //       height: 2,
              //       margin: const EdgeInsets.symmetric(horizontal: 30),
              //     ),
              itemCount: names.length),
        )
      ],
    );
  }
}
